include: package:lint/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false    
    avoid_classes_with_only_static_members: false
    sort_constructors_first: false
    prefer_single_quotes: true
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    lowercase_with_underscores: false
    file_names: false